<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Vessel3.Operator</RootNamespace>
    <AssemblyName>vessel3-operator</AssemblyName>

    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
    <StripSymbols>true</StripSymbols>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);IL2104;IL3053</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vessel3.Primitives\Vessel3.Primitives.csproj" />
    <ProjectReference Include="..\Vessel3.Client\Vessel3.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
  </ItemGroup>

</Project>
