{{- if and (not .Values.auth.secretName) (or .Values.auth.accessKey .Values.auth.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vessel3.fullname" . }}-admin-creds
  labels:
    {{- include "vessel3.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.auth.accessKey | default "admin" | quote }}
  secret-key: {{ .Values.auth.secretKey | default "vesseladminsecretkey" | quote }}
{{- end }}
