{{- if and (not .Values.auth.secretName) (include "vessel3.authSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vessel3.authSecretName" . }}
  labels:
    {{- include "vessel3.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.accessKeyKey }}: {{ .Values.auth.accessKey | quote }}
  {{ .Values.auth.secretKeyKey }}: {{ .Values.auth.secretKey | quote }}
{{- end }}
