apiVersion: v2
name: vessel3
description: Vessel3 High Performance Cloud Native Object Storage
type: application
version: 0.2.0
appVersion: "0.7.4"
keywords:
  - s3
  - storage
  - object-storage
  - cloud-native
  - aot
home: https://github.com/Nechja/Vessel3
maintainers:
  - name: Nechja
